### ISSUE TITLE
gsutil failing

### ISSUE THREAD

**Issue by gilmar** [GoogleCloudPlatform/bdutil#15]
Hi,

Since yesterday, and haven't changed anything on our side, we are getting the error message printed bellow when running 'gsutil' on machines deployed using bdutil.
We can fix this problem by running 'gcloud' command on the newly created machines.
It seems to be a problem introduced by the latest version of gsutil and affect bdutil as it does a "gcloud --quiet components update gsutil" at some point.
We are using the latest version (1.1.0), but it affects previous versions as well.

xxxx_xxxx_xxx@hadoop-m:~$ gsutil
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 59, in <module>
    bootstrapping.CommandStart('gsutil', component_id='gsutil')
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 188, in CommandStart
    metrics.Executions(command_name, version)
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", lin
e 230, in Executions
    _CollectGAEvent('Executions', command_name, version_string)
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", lin
e 193, in _CollectGAEvent
    collector = _MetricsCollector.GetCollector()
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", lin
e 51, in GetCollector
    _MetricsCollector._instance = _MetricsCollector()
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", lin
e 87, in __init__
    ('cid', _MetricsCollector._GetCID()),
  File "/usr/local/share/google/google-cloud-sdk/bin/bootstrapping/../../lib/googlecloudsdk/core/metrics.py", lin
e 111, in _GetCID
    with open(uuid_path, 'w') as f:
IOError: [Errno 2] No such file or directory: '/home/xxxx_xxxx_xxx/.config/gcloud/.metricsUUID'

**Comment by dennishuo** [comment]
Thanks for the report, indeed we've internally detected this issue and are tracking it at high priority; it affects non-Hadoop-related GCE usage as well. I'll update as more information and/or patches are released.

**Comment by gilmar** [comment]
Thanks for the status Dennis!

**Comment by dennishuo** [comment]
The fix was pushed this morning and now appears to successfully make it into any new deployments; the latest "Google Cloud SDK" version number is still the same, but the "core" component should now read 2015.02.05 vs the previous 2015.01.31:

```
$ gcloud version
Google Cloud SDK 0.9.46

bq 2.0.18
bq-nix 2.0.18
compute 2015.01.22
core 2015.02.05
core-nix 2015.01.22
dns 2015.01.22
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.8
gsutil-nix 4.7
sql 2015.01.31
```
